// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATn2Yseaxwf7gRhB7-L6XdR6Cgno_cHvg',
    appId: '1:767729462248:web:26aa91586bf060f06f925d',
    messagingSenderId: '767729462248',
    projectId: 'flutter-crud-b4e3b',
    authDomain: 'flutter-crud-b4e3b.firebaseapp.com',
    storageBucket: 'flutter-crud-b4e3b.appspot.com',
    measurementId: 'G-BBXM24KPLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCexZNLg6_ZH1rZsbfHT8klz5LZkSY2Tsk',
    appId: '1:767729462248:android:ee75b67437cc416b6f925d',
    messagingSenderId: '767729462248',
    projectId: 'flutter-crud-b4e3b',
    storageBucket: 'flutter-crud-b4e3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Tc0gvJi98AFhvMgCQqiQbzU0jgVGm5g',
    appId: '1:767729462248:ios:da519349cbe7c9a26f925d',
    messagingSenderId: '767729462248',
    projectId: 'flutter-crud-b4e3b',
    storageBucket: 'flutter-crud-b4e3b.appspot.com',
    iosClientId: '767729462248-6t1t82se9jhdr20buu2vcb3qktslp8hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMiniProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Tc0gvJi98AFhvMgCQqiQbzU0jgVGm5g',
    appId: '1:767729462248:ios:da519349cbe7c9a26f925d',
    messagingSenderId: '767729462248',
    projectId: 'flutter-crud-b4e3b',
    storageBucket: 'flutter-crud-b4e3b.appspot.com',
    iosClientId: '767729462248-6t1t82se9jhdr20buu2vcb3qktslp8hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMiniProjects',
  );
}
